### ISSUE TITLE
Keep getting this error when trying to log in, Information is correct

### ISSUE THREAD

**Issue by Panderz360** [siddvish21/aternos-discord-bot#3]
Traceback (most recent call last):
  File "C:\Users\Panderz\Pictures\Workspaces\aternos-discord-bot\.venv\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Panderz\Pictures\Workspaces\aternos-discord-bot\discord_bot_aternos.py", line 30, in on_message
    api = Client.from_credentials(os.getenv('USERNAME'), os.getenv('PASSWORD'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Panderz\Pictures\Workspaces\aternos-discord-bot\.venv\Lib\site-packages\python_aternos\atclient.py", line 146, in from_credentials
    return cls.from_hashed(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Panderz\Pictures\Workspaces\aternos-discord-bot\.venv\Lib\site-packages\python_aternos\atclient.py", line 111, in from_hashed
    raise CredentialsError(
python_aternos.aterrors.CredentialsError: Check your username and password
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Panderz\Pictures\Workspaces\aternos-discord-bot\.venv\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Panderz\Pictures\Workspaces\aternos-discord-bot\discord_bot_aternos.py", line 30, in on_message
    api = Client.from_credentials(os.getenv('USERNAME'), os.getenv('PASSWORD'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Panderz\Pictures\Workspaces\aternos-discord-bot\.venv\Lib\site-packages\python_aternos\atclient.py", line 146, in from_credentials
    return cls.from_hashed(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Panderz\Pictures\Workspaces\aternos-discord-bot\.venv\Lib\site-packages\python_aternos\atclient.py", line 111, in from_hashed
    raise CredentialsError(
python_aternos.aterrors.CredentialsError: Check your username and password

**Comment by siddvish21** [comment]
Hi there,

Thank you for reporting the issue you encountered with the Aternos Discord bot. After investigating the issue, I found that it was caused by incorrect credentials in the environment file.

To fix the issue, please update the .env file with the correct credentials for the Aternos server you are trying to connect to. Make sure to double-check the  login credentials to ensure that they are accurate. Once you have updated the credentials, you can restart the bot and try connecting to the Aternos server again.

If you continue to experience issues, please let me know and I would be happy to assist you further..

Thank you again for bringing this issue to my attention, and please don't hesitate to contact me if you have any further questions or concerns.

**Comment by siddvish21** [comment]
I accidently closed the issue . I will fix the issue soon.

**Comment by siddvish21** [comment]
Hi,

I believe the issue you're facing might be related to conflicts between the username environment variable in Windows and the username environment variable you're trying to set for your Aternos bot.

To solve this issue, you can try changing the name of your environment variable to something like ATERNOS_USERNAME and updating your bot code to use this new variable instead.

Please let me know if this helps, or if you have any further questions.

Thanks!

**Comment by Panderz360** [comment]
After Adjusting the code and fixing the .env file it worked perfectly thanks :D
